### ISSUE TITLE
Allow relative paths in .prrd.yaml

### ISSUE THREAD

**Issue by joshuaulrich** [eddelbuettel/prrd#17]
Currently, `workdir` can be a relative path but `libdir` cannot. This is because `prrd::dequeueJobs()` calls `setwd(cfg$workdir)` before running `R CMD check`, which then means `libdir`'s relative location is no longer correct. We could use `normalizePath(cfg$libdir)` to get the full path before calling `setwd(cfg$workdir)`. Thoughts? I can submit a PR if you'd like.

My config file is:

```yaml
default:
  workdir: "./workdir"
  libdir: "./lib"
  debug: "false"
  verbose: "false"
```

And my directory layout is:

```
pwd/
    libdir/
    workdir/
```

**Comment by eddelbuettel** [comment]
Yes -- some of that is clumsier than it should be.  What you suggest above sounds sensible.
