### ISSUE TITLE
Edge cases: No revdep, Pkg checked not installed, Pkg not on CRAN

### ISSUE THREAD

**Issue by coatless** [eddelbuettel/prrd#6]
Listing the edge cases in one issue as they have the same underlying error message and I'm trying to exceed 200 words :sunglasses:

### Issues
 
1. Package lacks reverse dependencies. c.f.  [`pkgKitten`](https://cran.r-project.org/web/packages/pkgKitten/)
2. Package not installed, could be from a typo et cetera. Would be nice if there was a warning... 
3. Package not on CRAN

### Error Diagnostics

All edge cases give warnings like:

```r
inqueue <- enqueueJobs("pkgKitten", ".")
# Error: title is not a string (length 1 character)

outqueue <- dequeueJobs("pkgKitten", ".")
# NA_NA started at 2018-01-23 00:01:13 Warning in download.packages(tok[1], ".", quiet = TRUE) : 
# no package ‘NA’ at the repositories
```

### Protection

Largely the case since:

```bash
Empty data.table (0 rows) of 2 cols: Package,Version
```

will be empty during:

https://github.com/eddelbuettel/prrd/blob/e936686015dc40e517d83e49c0fde9b507218a5c/R/enqueue.R#L36-L40

I think one bit we discussed was adding `with = FALSE` (data.table's `drop = FALSE`) inside the `work` subset

**Comment by eddelbuettel** [comment]
Part is fixiing `1:n` for the loop to `seq_len(nrow(work))` but that still needs special for empty, and single row.

**Comment by eddelbuettel** [comment]
"Package not on CRAN" is not valid; you may have different `options(repos)` -- we have a local-to-work `drat` repo at work.  "Somewhere in `available.packages()` output" is a better test.

**Comment by eddelbuettel** [comment]
"Not installed" is not valid I think.

**Comment by eddelbuettel** [comment]
This really reduced down to one additional check, and that I made.  The n=1 case is taken care of by data.table.

**Comment by coatless** [comment]
Great! I'll give it a whirl and see if I can break it more 😃
